### ISSUE TITLE
Update des lokalen Haltestellen-Cache beim ersten öffnen der App.

### ISSUE THREAD

**Issue by GuennisHueftgold** [GuennisHueftgold/ManniSpotter#1]
Derzeit muss man auf ein automatisches Synchronisieren des Caches warten oder dieses manuell über das entsprechende Einstellungsmenü leisten. Mögliche Lösungen sind:

- als asset eine SQL-Datenbank mitliefern, die vorher populiert wurde
- den ersten Start registrieren und ein Update beim ersten Start erzwingen. Möglichen trigger in den SharedPreferences ablegen.

**Comment by Voltoviper** [comment]
Ich würde die 2. Möglichkeit bevorzugen. Dann könntest im gleichen Zuge auch beim Start einen Favoriten wählen lassen.

**Comment by GuennisHueftgold** [comment]
@Voltoviper  Verzeihung. Dein Kommentar ist untergegangen damals.

Ich habe jetzt zunächst die "Einfache Version" integriert mit ac3b9e155cfa5c60eb773ccd21d877c377659b4a aber du hast recht. Ein ViewPager mit mehreren Panels zum Synchronisieren und ersten Setup wäre wohl die optimalste Lösung.

Ich werde jetzt erstmal für den Release von 1.1.0 dieses Issue schließen und einen neues Öffnen mit deinem Vorschlag für 1.2.0.
